title: Syed Khalid Tipu Razvi | Cybersecurity Portfolio
description: Welcome to my cybersecurity knowledge base — a hub for documentation, projects, and writeups that showcase offensive and defensive security skills, including penetration testing, incident response, threat analysis, and automation for network defense.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
