title: Syed Khalid Tipu Razvi | Cybersecurity Portfolio
description: A cybersecurity portfolio highlighting my offensive and defensive security skills — featuring penetration testing labs, incident response projects, security research, and automation scripts focused on network defense, threat analysis, and ethical hacking.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
